// Collects the external asset blobs a world actually uses and encodes them for
// embedding in a worldpack. Primitives (cube/sphere/…) are regenerated by the
// runtime and never travel. Unused library assets are excluded. Missing blobs
// are reported, never silently dropped.
//
// Node-safe: uses Blob.arrayBuffer() (Node 18+ / browsers) and a base64 codec
// that prefers Buffer when present and falls back to btoa/atob.

import { isPrimitiveAssetId } from "../assets/AssetTypes.js";

/**
 * Unique external (non-primitive) assetRefs referenced by placed objects.
 * Returns an ordered list so embedding is deterministic.
 */
export function collectUsedAssetRefs(document) {
  const refs = [];
  const seen = new Set();
  for (const object of document?.objects ?? []) {
    const ref = typeof object?.assetRef === "string" ? object.assetRef : null;
    if (!ref || isPrimitiveAssetId(ref) || seen.has(ref)) continue;
    seen.add(ref);
    refs.push(ref);
  }
  return refs;
}

/**
 * Resolve, fetch and base64-encode every used external asset.
 *
 * @param {object} document      sanitized WorldDocument v2
 * @param {object} assetLibrary  AssetLibrary (or compatible: get(id) + store.getBlob(id))
 * @returns {Promise<{ embedded: object[], missing: object[], unusedCount: number }>}
 */
export async function collectBuildAssets(document, assetLibrary) {
  const usedRefs = collectUsedAssetRefs(document);
  const embedded = [];
  const missing = [];

  for (const ref of usedRefs) {
    const metadata = assetLibrary?.get?.(ref) ?? null;
    const blob = await getBlobForRef(assetLibrary, ref);
    if (!metadata || !blob) {
      missing.push({
        id: ref,
        type: metadata?.type ?? null,
        name: metadata?.name ?? ref,
        reason: metadata ? "no local blob data" : "asset not found in library",
      });
      continue;
    }
    embedded.push({
      id: ref,
      type: metadata.type,
      kind: metadata.kind ?? null,
      name: metadata.name ?? ref,
      mimeType: metadata.mimeType ?? blob.type ?? "application/octet-stream",
      sizeBytes: Number.isFinite(metadata.sizeBytes) && metadata.sizeBytes > 0 ? metadata.sizeBytes : blob.size,
      bounds: metadata.bounds ?? null,
      defaultColliderType: metadata.defaultColliderType ?? null,
      defaultExclusion: metadata.defaultExclusion ?? null,
      runtime: metadata.runtime ?? null,
      animation: metadata.animation ?? null,
      dataBase64: await blobToBase64(blob),
    });
  }

  return { embedded, missing, unusedCount: countUnusedAssets(assetLibrary, usedRefs) };
}

function countUnusedAssets(assetLibrary, usedRefs) {
  const used = new Set(usedRefs);
  const all = assetLibrary?.list?.() ?? [];
  return all.filter((asset) => !isPrimitiveAssetId(asset.id) && asset.type !== "primitive" && !used.has(asset.id)).length;
}

async function getBlobForRef(assetLibrary, ref) {
  const store = assetLibrary?.store;
  if (!store?.getBlob) return null;
  try {
    return (await store.getBlob(ref)) ?? null;
  } catch (error) {
    console.warn(`Could not read blob for asset "${ref}"`, error);
    return null;
  }
}

// --- base64 codec (Node + browser) ------------------------------------------

export async function blobToBase64(blob) {
  const buffer = await blob.arrayBuffer();
  return arrayBufferToBase64(buffer);
}

export function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  if (typeof Buffer !== "undefined") return Buffer.from(bytes).toString("base64");
  let binary = "";
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk));
  }
  return btoa(binary);
}

export function base64ToUint8Array(base64) {
  const clean = String(base64 ?? "");
  if (typeof Buffer !== "undefined") return new Uint8Array(Buffer.from(clean, "base64"));
  const binary = atob(clean);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}
