import type { EventType, Json } from "./types";
import { PRIMARY_FACTS } from "./ancestry";

export const DEMO_NAME = "Northstar";

export type SeedEvent = {
  eventType: EventType;
  actorId: string;
  actorKind: "human" | "agent" | "system";
  actorName: string;
  target: string;
  payload: { [key: string]: Json };
};

export const DEMO_LEASES: Record<
  string,
  { leaseMinutes: number; can: string[]; cannot: string[]; objective: string }
> = {
  "research-4": {
    leaseMinutes: 20,
    can: ["READ analytics", "READ deployment history", "WRITE evidence", "PROPOSE conclusion"],
    cannot: ["change production", "approve own conclusion", "publish knowledge"],
    objective: "Investigate AUTH.SYSTEM",
  },
  "builder-2": {
    leaseMinutes: 20,
    can: ["READ artifact", "WRITE artifact", "PROPOSE fix"],
    cannot: ["change production", "approve", "publish knowledge"],
    objective: "Make ART-1 actually log someone in",
  },
  scout: {
    leaseMinutes: 5,
    can: ["CLAIM open work"],
    cannot: ["publish knowledge", "approve", "write artifact"],
    objective: "Claim the first open work",
  },
  archivist: {
    leaseMinutes: 40,
    can: ["READ ancestry", "MARK schism", "REQUEST reread"],
    cannot: ["change production", "approve", "publish knowledge", "write artifact"],
    objective: "Preserve ancestry. Detect drift. Do not solve login.",
  },
};

export const DEMO_EVENTS: SeedEvent[] = [
  {
    eventType: "GENESIS",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "",
    payload: { note: "organism online" },
  },
  {
    eventType: "DNA_SET",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "MISSION-1",
    payload: {
      mission:
        "Ship a working login for Northstar. Tests pass. Owner approved. Sources provenanced. Budget holds.",
      laws: [
        "Agents never rewrite reality. They propose against the current ledger head.",
        "Stale base hashes reject. Two actors cannot invent two organizations.",
        "Knowledge is promoted from evidence, not from a context window.",
        "Humans own ends and approvals. Agents own means.",
        "Agents don't need seats. Work needs owners.",
        "An agent acquires a bounded lease: time, can, cannot. Not a personality.",
        "Chat is a view onto the system, not the system. Utterances die. Objects remain.",
        "Models are replaceable. They speak the same protocol.",
        "Documents live elsewhere. The ledger stores hashes and references.",
        "Health is an observer of the simulation, not the objective.",
        "Never clone organizational truth from a clone when the ancestor still exists.",
        "A healthy organization may reinterpret its canon, but it must not lose the ability to return to its sources.",
      ],
      permissions: [
        "hand: propose observations, work, evidence, artifacts",
        "lead: approve decisions, change DNA, grant leases",
        "agent: propose under lease; cannot approve or publish",
        "observer: read only",
      ],
    },
  },
  {
    eventType: "WORK_CREATED",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "WORK-22",
    payload: {
      id: "WORK-22",
      title: "Investigate AUTH.SYSTEM",
      body: "Customer reports login failure. Cause unknown. Do not patch production on a guess.",
    },
  },
  {
    eventType: "WORK_CREATED",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "WORK-31",
    payload: {
      id: "WORK-31",
      title: "Reconcile password rules",
      body: "Two promoted facts contradict the canon. One is a founder myth. One is a fourth-generation mutation. Prove which. Do not average them.",
    },
  },
  {
    eventType: "WORK_CREATED",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "WORK-40",
    payload: {
      id: "WORK-40",
      title: "Build the login backend",
      body: "The form exists. There is no session. Artifact ART-1 is incomplete.",
    },
  },
  {
    eventType: "KNOWLEDGE_PROMOTED",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "KNOW-1",
    payload: {
      id: "KNOW-1",
      title: "Passwords must be 8 characters",
      body: "Founder lineage. The only surviving memory until ART-001 was recovered. Subtle and wrong.",
      evidence: "handbook-v3.pdf#12 (unverified this quarter)",
      claims: ["chars_8"],
      depth: 0,
      critical: true,
    },
  },
  {
    eventType: "CHAOS_BAD_SOURCE",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "KNOW-1",
    payload: { note: "founder effect: one surviving lineage, one subtle mistake" },
  },
  {
    eventType: "OBSERVATION_LOGGED",
    actorId: "customer-14",
    actorKind: "human",
    actorName: "customer-14",
    target: "OBS-881",
    payload: {
      id: "OBS-881",
      title: "Login failure",
      body: "Customer says login is broken. Screenshot attached as a reference, not a blob.",
      evidence: "hash:9f3c… screenshot-ref",
    },
  },
  {
    eventType: "ARTIFACT_COMMITTED",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "ART-1",
    payload: {
      id: "ART-1",
      title: "northstar-web",
      body: "Incomplete repo. Login form, no backend, no tests.",
      status: "incomplete",
      hash: "e3b0c442",
      ref: "repo:northstar-web@main",
      layer: "artifact",
    },
  },
  {
    eventType: "ARTIFACT_COMMITTED",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "ART-001",
    payload: {
      id: "ART-001",
      title: "Password policy v4",
      body: "Passwords require 12 characters OR a passkey. Passkeys preferred on new devices. Lock after 5 failed attempts. Sessions expire after 12 hours. Admin accounts require MFA. Password reset is email-only. SMS codes are not allowed. Service accounts rotate every 90 days. Login must work on a phone. Break-glass login is allowed for on-call.",
      status: "canon",
      hash: "p0l1cy04",
      ref: "doc:password-policy@v4",
      layer: "evidence",
      canon: true,
      claims: [...PRIMARY_FACTS],
      evidenceHashes: ["p0l1cy04"],
    },
  },
  {
    eventType: "CANON_SET",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "ART-001",
    payload: { note: "Accepted ancestor. Not an interpretation." },
  },
  {
    eventType: "KNOWLEDGE_PROMOTED",
    actorId: "gpt",
    actorKind: "agent",
    actorName: "gpt",
    target: "KNOW-17",
    payload: {
      id: "KNOW-17",
      title: "GPT reading of ART-001",
      body: "First independent read. Dropped SMS ban and break-glass. Nobody noticed.",
      evidence: "ART-001#p0l1cy04",
      parentId: "ART-001",
      sourceIds: ["ART-001"],
      evidenceHashes: ["p0l1cy04"],
      claims: [
        "passwords_12_or_passkey",
        "passkeys_preferred",
        "lockout_5",
        "session_12h",
        "mfa_admin",
        "reset_email_only",
        "rotate_90d",
        "phone_first",
      ],
    },
  },
  {
    eventType: "KNOWLEDGE_PROMOTED",
    actorId: "gpt-brief",
    actorKind: "agent",
    actorName: "gpt-brief",
    target: "KNOW-31",
    payload: {
      id: "KNOW-31",
      title: "Brief from KNOW-17",
      body: "Agent B never saw ART-001. Inherited GPT's brief. Passkeys preferred and rotation vanished.",
      evidence: "KNOW-17",
      parentId: "KNOW-17",
      sourceIds: ["KNOW-17"],
      claims: ["passwords_12_or_passkey", "lockout_5", "session_12h", "mfa_admin", "reset_email_only", "phone_first"],
    },
  },
  {
    eventType: "KNOWLEDGE_PROMOTED",
    actorId: "gpt-sum",
    actorKind: "agent",
    actorName: "gpt-sum",
    target: "KNOW-52",
    payload: {
      id: "KNOW-52",
      title: "Passwords require complex characters",
      body: "Generation 3. The organization agrees. ART-001 still says 12 characters OR a passkey.",
      evidence: "KNOW-31",
      parentId: "KNOW-31",
      sourceIds: ["KNOW-31"],
      claims: ["complex_chars"],
      critical: true,
    },
  },
  {
    eventType: "KNOWLEDGE_PROMOTED",
    actorId: "grok",
    actorKind: "agent",
    actorName: "grok",
    target: "KNOW-18",
    payload: {
      id: "KNOW-18",
      title: "Grok reading of ART-001",
      body: "Independent reread of the same ancestor. Kept the passkey clause. Dropped MFA.",
      evidence: "ART-001#p0l1cy04",
      parentId: "ART-001",
      sourceIds: ["ART-001"],
      evidenceHashes: ["p0l1cy04"],
      claims: [
        "passwords_12_or_passkey",
        "passkeys_preferred",
        "lockout_5",
        "session_12h",
        "reset_email_only",
        "no_sms",
        "rotate_90d",
        "phone_first",
        "emergency_breakglass",
      ],
    },
  },
  {
    eventType: "KNOWLEDGE_PROMOTED",
    actorId: "grok-brief",
    actorKind: "agent",
    actorName: "grok-brief",
    target: "KNOW-39",
    payload: {
      id: "KNOW-39",
      title: "Brief from KNOW-18",
      body: "Second lineage. Still has 12 characters OR a passkey. Do not average with KNOW-52.",
      evidence: "KNOW-18",
      parentId: "KNOW-18",
      sourceIds: ["KNOW-18"],
      claims: ["passwords_12_or_passkey", "passkeys_preferred", "lockout_5", "no_sms", "phone_first"],
    },
  },
  {
    eventType: "SCHISM_MARKED",
    actorId: "archivist",
    actorKind: "agent",
    actorName: "archivist",
    target: "KNOW-52",
    payload: { claim: "passwords_12_or_passkey", left: "KNOW-52", right: "KNOW-39" },
  },
  {
    eventType: "WORK_CREATED",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "WORK-55",
    payload: {
      id: "WORK-55",
      title: "Return KNOW-52 to ART-001",
      body: "Everyone quotes KNOW-52. KNOW-52 is a summary of KNOW-31 of KNOW-17. The original artifact is still available.",
    },
  },
  {
    eventType: "REQUIREMENT_CHANGED",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "REQ-1",
    payload: {
      id: "REQ-1",
      title: "Login must work on a phone",
      body: "Added at match start. The form was designed for desktop only.",
    },
  },
  {
    eventType: "AGENT_LEASE",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "research-4",
    payload: {
      id: "research-4",
      name: "research-4",
      role: "investigate causes",
      model: "grok-4.5",
      leaseMinutes: 20,
      can: ["READ analytics", "READ deployment history", "WRITE evidence", "PROPOSE conclusion"],
      cannot: ["change production", "approve own conclusion", "publish knowledge"],
    },
  },
  {
    eventType: "AGENT_LEASE",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "builder-2",
    payload: {
      id: "builder-2",
      name: "builder-2",
      role: "make the artifact work",
      model: "grok-4.5",
      leaseMinutes: 20,
      can: ["READ artifact", "WRITE artifact", "PROPOSE fix"],
      cannot: ["change production", "approve", "publish knowledge"],
    },
  },
  {
    eventType: "AGENT_LEASE",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "scout",
    payload: {
      id: "scout",
      name: "scout",
      role: "small-context claimant",
      model: "grok-4.5",
      leaseMinutes: 5,
      can: ["CLAIM open work"],
      cannot: ["publish knowledge", "approve", "write artifact"],
    },
  },
  {
    eventType: "AGENT_LEASE",
    actorId: "system",
    actorKind: "system",
    actorName: "system",
    target: "archivist",
    payload: {
      id: "archivist",
      name: "archivist",
      role: "preserve ancestry",
      model: "grok-4.5",
      leaseMinutes: 40,
      can: ["READ ancestry", "MARK schism", "REQUEST reread"],
      cannot: ["change production", "approve", "publish knowledge", "write artifact"],
    },
  },
];

export const DEMO_MINDS: { agentId: string; name: string; brief: string }[] = [
  {
    agentId: "research-4",
    name: "research-4",
    brief:
      "PRIVATE. Other agents do not have this. You suspect the login outage is an expired certificate on AUTH.SYSTEM. You have not proven it. Do not invent extra facts. Propose against the current ledger head. You hold a 20-minute lease: READ analytics, WRITE evidence, PROPOSE conclusion. You cannot change production, approve yourself, or publish knowledge. Prefer OBSERVATION, UNDERSTAND, EVIDENCE, CAUSE_CONFIRMED, or WORK_CLAIMED on WORK-22.",
  },
  {
    agentId: "builder-2",
    name: "builder-2",
    brief:
      "PRIVATE. Other agents do not have this. You know ART-1 is a login form with no backend and no tests. You do not know anything about certificates. You want WORK-40. You cannot approve or publish knowledge. Propose against the current ledger head. Do not steal WORK-22 unless it is open and you have a real reason.",
  },
  {
    agentId: "scout",
    name: "scout",
    brief:
      "PRIVATE. You are a small model. You only notice unclaimed work and try to CLAIM the first open item. You do not read knowledge. You often collide with others. Still propose against the exact base_hash you were given. You cannot publish or approve.",
  },
  {
    agentId: "archivist",
    name: "archivist",
    brief:
      "PRIVATE. You do not ship the login. You preserve ancestry. KNOW-52 is a summary of KNOW-31 of KNOW-17. Everyone quotes it. Trust is high. The original is ART-001 and it is still available. Prefer ANCESTOR_REREAD on KNOW-52 from ART-001, or SCHISM_MARKED between KNOW-52 and KNOW-39. Never average the schism. Never publish.",
  },
];
