export const DNA_VERSION = 1;

export const EVENT_TYPES = Object.freeze({
  ORG_CREATED: 'ORG_CREATED',
  ACTOR_REGISTERED: 'ACTOR_REGISTERED',
  ROLE_GRANTED: 'ROLE_GRANTED',
  MISSION_CREATED: 'MISSION_CREATED',
  MISSION_UPDATED: 'MISSION_UPDATED',
  WORK_CREATED: 'WORK_CREATED',
  WORK_CLAIMED: 'WORK_CLAIMED',
  WORK_RELEASED: 'WORK_RELEASED',
  WORK_BLOCKED: 'WORK_BLOCKED',
  WORK_COMPLETED: 'WORK_COMPLETED',
  OBSERVATION_RECORDED: 'OBSERVATION_RECORDED',
  EVIDENCE_ATTACHED: 'EVIDENCE_ATTACHED',
  DECISION_PROPOSED: 'DECISION_PROPOSED',
  DECISION_APPROVED: 'DECISION_APPROVED',
  DECISION_REJECTED: 'DECISION_REJECTED',
  ARTIFACT_COMMITTED: 'ARTIFACT_COMMITTED',
  KNOWLEDGE_PROPOSED: 'KNOWLEDGE_PROPOSED',
  KNOWLEDGE_PROMOTED: 'KNOWLEDGE_PROMOTED',
  KNOWLEDGE_RETRACTED: 'KNOWLEDGE_RETRACTED',
  CONSTRAINT_SET: 'CONSTRAINT_SET',
  CONSTRAINT_CLEARED: 'CONSTRAINT_CLEARED',
  AGENT_STATUS_SET: 'AGENT_STATUS_SET',
  LEASE_EXPIRED: 'LEASE_EXPIRED',
  BRANCH_CREATED: 'BRANCH_CREATED',
  BRANCH_MERGED: 'BRANCH_MERGED',
  HEALTH_CHANGED: 'HEALTH_CHANGED'
});

export const ROLES = Object.freeze({
  ADMIN: 'admin',
  HUMAN: 'human',
  AGENT: 'agent',
  REVIEWER: 'reviewer',
  OBSERVER: 'observer'
});

export const PERMISSIONS = Object.freeze({
  READ: 'read',
  PROPOSE: 'propose',
  CLAIM: 'claim',
  EXECUTE: 'execute',
  APPROVE: 'approve',
  KNOWLEDGE_PROMOTE: 'knowledge_promote',
  MANAGE_ACTORS: 'manage_actors',
  MANAGE_DNA: 'manage_dna',
  BRANCH: 'branch',
  MERGE: 'merge'
});

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.HUMAN]: [
    PERMISSIONS.READ, PERMISSIONS.PROPOSE, PERMISSIONS.CLAIM,
    PERMISSIONS.EXECUTE, PERMISSIONS.APPROVE, PERMISSIONS.BRANCH
  ],
  [ROLES.AGENT]: [
    PERMISSIONS.READ, PERMISSIONS.PROPOSE, PERMISSIONS.CLAIM,
    PERMISSIONS.EXECUTE, PERMISSIONS.BRANCH
  ],
  [ROLES.REVIEWER]: [
    PERMISSIONS.READ, PERMISSIONS.PROPOSE, PERMISSIONS.APPROVE,
    PERMISSIONS.KNOWLEDGE_PROMOTE, PERMISSIONS.MERGE
  ],
  [ROLES.OBSERVER]: [PERMISSIONS.READ]
});

export const EVENT_PERMISSION = Object.freeze({
  [EVENT_TYPES.ORG_CREATED]: PERMISSIONS.MANAGE_DNA,
  [EVENT_TYPES.ACTOR_REGISTERED]: PERMISSIONS.MANAGE_ACTORS,
  [EVENT_TYPES.ROLE_GRANTED]: PERMISSIONS.MANAGE_ACTORS,
  [EVENT_TYPES.MISSION_CREATED]: PERMISSIONS.PROPOSE,
  [EVENT_TYPES.MISSION_UPDATED]: PERMISSIONS.PROPOSE,
  [EVENT_TYPES.WORK_CREATED]: PERMISSIONS.PROPOSE,
  [EVENT_TYPES.WORK_CLAIMED]: PERMISSIONS.CLAIM,
  [EVENT_TYPES.WORK_RELEASED]: PERMISSIONS.CLAIM,
  [EVENT_TYPES.WORK_BLOCKED]: PERMISSIONS.EXECUTE,
  [EVENT_TYPES.WORK_COMPLETED]: PERMISSIONS.EXECUTE,
  [EVENT_TYPES.OBSERVATION_RECORDED]: PERMISSIONS.PROPOSE,
  [EVENT_TYPES.EVIDENCE_ATTACHED]: PERMISSIONS.PROPOSE,
  [EVENT_TYPES.DECISION_PROPOSED]: PERMISSIONS.PROPOSE,
  [EVENT_TYPES.DECISION_APPROVED]: PERMISSIONS.APPROVE,
  [EVENT_TYPES.DECISION_REJECTED]: PERMISSIONS.APPROVE,
  [EVENT_TYPES.ARTIFACT_COMMITTED]: PERMISSIONS.EXECUTE,
  [EVENT_TYPES.KNOWLEDGE_PROPOSED]: PERMISSIONS.PROPOSE,
  [EVENT_TYPES.KNOWLEDGE_PROMOTED]: PERMISSIONS.KNOWLEDGE_PROMOTE,
  [EVENT_TYPES.KNOWLEDGE_RETRACTED]: PERMISSIONS.KNOWLEDGE_PROMOTE,
  [EVENT_TYPES.CONSTRAINT_SET]: PERMISSIONS.APPROVE,
  [EVENT_TYPES.CONSTRAINT_CLEARED]: PERMISSIONS.APPROVE,
  [EVENT_TYPES.AGENT_STATUS_SET]: PERMISSIONS.EXECUTE,
  [EVENT_TYPES.LEASE_EXPIRED]: PERMISSIONS.EXECUTE,
  [EVENT_TYPES.BRANCH_CREATED]: PERMISSIONS.BRANCH,
  [EVENT_TYPES.BRANCH_MERGED]: PERMISSIONS.MERGE,
  [EVENT_TYPES.HEALTH_CHANGED]: PERMISSIONS.EXECUTE
});

export const DEFAULT_HEALTH = Object.freeze({
  integrity: 100,
  coherence: 100,
  trust: 100,
  energy: 100,
  security: 100,
  knowledge_quality: 100,
  mission_progress: 0
});

export const DNA = Object.freeze({
  version: DNA_VERSION,
  laws: [
    'The ledger is authoritative; chat and model context are not.',
    'Actors submit intent; validators decide whether reality changes.',
    'Knowledge requires provenance and promotion before becoming shared truth.',
    'Agents may not approve their own decision proposals.',
    'Exclusive work can have one active owner lease per branch.',
    'All accepted changes reference the branch head they were based on.',
    'Artifacts are referenced by immutable digest; large bytes live outside the ledger.',
    'Replay from DNA plus ledger must reconstruct the same projected state.'
  ]
});

export function permissionsForRoles(roles = []) {
  return new Set(roles.flatMap(role => ROLE_PERMISSIONS[role] || []));
}
